### ISSUE TITLE
Search type selector doesn't work properly

### ISSUE THREAD

**Issue by chosak** [cfpb/crawsqueal#14]
The "Things to search for" selector in the search sidebar doesn't seem to work properly. If you select "HTML" or "Components", the resulting search still goes to the "Links" view:

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/654645/172211119-5af55dc2-2ca2-43d9-9af3-06b0b6a38277.png">

The search should modify the `search_type` parameter in the query string -- you can manually trigger the HTML/components search by setting `?search_type=html` or `?search_type=components`.

**Comment by contolini** [comment]
Yes! This needs to be fixed. Currently it's two separate forms. Very dumb.

Couple options I see:

1. Combine the forms at the HTML level by having all the form elements contained within a single `<form>` element and have two submit buttons. This is a pain due to the page's layout.
1. Continue having two separate forms but use JS to sync the forms by adding `type=hidden` form elements that get updated whenever an option or search term is changed.
1. Remove the `Update` button and use AJAX to update the results in real-time when sidebar options are changed. This is what [iRegs does](https://www.consumerfinance.gov/rules-policy/regulations/search-regulations/results/?q=money&regs=1005) (try changing a sidebar option). There's a [separate endpoint](https://github.com/cfpb/consumerfinance.gov/blob/86df69721b3c64b2f69d88d6f5fbd60dd3c3d39d/cfgov/regulations3k/models/pages.py#L60-L61) that returns partial HTML that the front-end [fetches and injects into the DOM](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/regulations3k/js/search.js#L126-L138).

iRegs has a no-JS fallback that shows an `Update` button for when JS is disabled by the user. Our template is based on iRegs but has no AJAX functionality, hence our ugly update button.

Option 2 above is easiest to implement so I'll start on that right now.
